language: c
os:
 - linux
sudo: true
notifications:
 email:
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    
env:
 - CC=gcc-4.9 BUILD_TYPE=Release CONAN="-s compiler.version=4.9 -s build_type=Release"
 - CC=gcc-4.9 BUILD_TYPE=Debug   CONAN="-s compiler.version=4.9 -s build_type=Debug"

install:
 - wget https://s3-eu-west-1.amazonaws.com/conanio-production/downloads/conan-ubuntu-64_0_13_1.deb -O conan.deb || exit 1
 - sudo dpkg -i conan.deb || exit 1
 - rm conan.deb || exit 1
 - conan --version

 - wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz
 - tar -xzf cmake-3.0.2-Linux-64.tar.gz
 - sudo cp -fR cmake-3.0.2-Linux-64/* /usr
 - rm -rf cmake-3.0.2-Linux-64
 - rm cmake-3.0.2-Linux-64.tar.gz

script:
 - mkdir build
 - pushd build
 - conan install -s compiler=gcc $CONAN ../src || exit 1
 - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE || exit 1
 - cmake --build . -- -j2 || exit 1
 - pushd bin
 - ./test_main || exit 1
